# Generated by Django 2.2.16 on 2022-09-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('url', models.SlugField(unique=True)),
                ('date', models.CharField(max_length=200)),
                ('parentId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childId', to='api.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.SlugField(unique=True)),
                ('date', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('parentId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Folder')),
            ],
        ),
    ]
