# Generated by Django 2.2.16 on 2022-09-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='parentId',
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
    ]
