# Generated by Django 2.2.16 on 2022-09-12 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220912_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='parentId',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Folder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
