# Generated by Django 2.2.16 on 2022-09-13 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_auto_20220912_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'FILE'), (1, 'FOLDER')])),
                ('url', models.SlugField(default=None, max_length=255, unique=True)),
                ('size', models.IntegerField(default=None, max_length=6)),
                ('date', models.DateTimeField(default=None)),
                ('parentId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.File')),
            ],
        ),
    ]
