# Generated by Django 2.2.16 on 2022-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.SlugField(default=None, max_length=255),
        ),
    ]
