# Generated by Django 2.2.16 on 2022-09-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220913_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
