# Generated by Django 2.2.16 on 2022-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220913_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.SlugField(default=None, max_length=255, null=True),
        ),
    ]
