# Generated by Django 2.2.16 on 2022-09-13 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220913_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parentId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.File'),
        ),
    ]
