# Generated by Django 2.2.16 on 2022-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220913_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('FILE', 'FILE'), ('FOLDER', 'FOLDER')], max_length=6),
        ),
    ]
