# Generated by Django 2.2.16 on 2022-09-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220913_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='date',
            new_name='updateDate',
        ),
    ]
