# Generated by Django 2.2.16 on 2022-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220913_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
