# Generated by Django 2.2.16 on 2022-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220913_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
