# Generated by Django 2.2.16 on 2022-09-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220913_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='updateDate',
            new_name='date',
        ),
    ]
