# Generated by Django 2.2.16 on 2022-09-15 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220914_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='changes_history',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_file_version', to='api.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
